# Generated by Django 5.2.10 on 2026-05-03 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        help_text="Stored in encrypted format (AES-128).",
                        verbose_name="Encrypted Email Address",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Email Hash",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Nickname",
                    ),
                ),
                (
                    "currency_preference",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("UAH", "Ukrainian Hryvnia"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("phone_number", models.TextField(verbose_name="Phone Number")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        help_text="Encrypted email address of the user requesting password reset.",
                        verbose_name="Encrypted Email Address",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Email Hash"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit OTP code for password reset.",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_hash", "code"],
                        name="accounts_pa_email_h_5fa3f8_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_pa_expires_d8be21_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistrationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        help_text="Encrypted email address of the user registering.",
                        verbose_name="Encrypted Email Address",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Email Hash"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit OTP code for registration verification.",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
            ],
            options={
                "verbose_name": "Registration OTP",
                "verbose_name_plural": "Registration OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_hash", "code"],
                        name="accounts_re_email_h_4cb246_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_re_expires_b37fcb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SMSVerificationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number in E.164 format",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit OTP code for 2FA verification.",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Track failed verification attempts",
                        verbose_name="Failed Attempts",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_2fa_otp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Verification OTP",
                "verbose_name_plural": "SMS Verification OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code"], name="accounts_sm_user_id_e070d7_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_sm_expires_841daa_idx"
                    ),
                ],
            },
        ),
    ]
