# Generated by Django 5.2.10 on 2026-01-17 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. Email address is used as the primary identifier.",
                        max_length=255,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "currency_preference",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("UAH", "Ukrainian Hryvnia"),
                        ],
                        default="USD",
                        help_text="Preferred currency for displaying financial data.",
                        max_length=3,
                        verbose_name="Currency Preference",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the user registered.",
                        verbose_name="Date Joined",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the admin site.",
                        verbose_name="Staff Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the user requesting password reset.",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit OTP code for password reset.",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the OTP code was generated.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Timestamp when the OTP code expires (10 minutes after creation).",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this OTP code has been used for password reset.",
                        verbose_name="Used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the OTP code was used.",
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "code"], name="accounts_pa_email_d46b34_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_pa_expires_d8be21_idx"
                    ),
                ],
            },
        ),
    ]
