# Generated by Django 5.2.10 on 2026-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Enabled"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.TextField(
                help_text="Stored in encrypted format (AES-128).",
                unique=True,
                verbose_name="Encrypted Email Address",
            ),
        ),
    ]
