# Generated by Django 5.2.10 on 2026-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Display name for the user. Must be unique.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Nickname",
            ),
        ),
    ]
