# Generated by Django 5.2.10 on 2026-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        help_text="Encrypted email address of the user registering.",
                        verbose_name="Encrypted Email Address",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Email Hash"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit OTP code for registration verification.",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
            ],
            options={
                "verbose_name": "Registration OTP",
                "verbose_name_plural": "Registration OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_hash", "code"],
                        name="accounts_re_email_h_4cb246_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_re_expires_b37fcb_idx"
                    ),
                ],
            },
        ),
    ]
