# Generated by Django 5.2.10 on 2026-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional monthly spending limit for predictive budget alerts.",
                max_digits=12,
                null=True,
                verbose_name="Monthly Budget",
            ),
        ),
    ]
