# Generated by Django 5.2.10 on 2026-05-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSVerificationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number in E.164 format",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit OTP code for 2FA verification.",
                        max_length=6,
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Track failed verification attempts",
                        verbose_name="Failed Attempts",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_2fa_otp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Verification OTP",
                "verbose_name_plural": "SMS Verification OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code"], name="accounts_sm_user_id_e070d7_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_sm_expires_841daa_idx"
                    ),
                ],
            },
        ),
    ]
