# Generated by Django 5.2.10 on 2026-04-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="anomaly_score",
            field=models.FloatField(
                blank=True,
                help_text="Isolation Forest anomaly score (lower = more anomalous).",
                null=True,
                verbose_name="Anomaly Score",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_encrypted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the description field is Fernet-encrypted at rest.",
                verbose_name="Is Encrypted",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_suspicious",
            field=models.BooleanField(
                default=False,
                help_text="Flagged by Isolation Forest anomaly detection.",
                verbose_name="Is Suspicious",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="predicted_category",
            field=models.ForeignKey(
                blank=True,
                help_text="ML-predicted category from auto-categorization service.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predicted_transactions",
                to="transactions.category",
                verbose_name="Predicted Category",
            ),
        ),
    ]
