# Generated by Django 5.2.10 on 2026-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_advisor_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="Name of the category (Encrypted at rest)",
                verbose_name="Category Name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.TextField(
                help_text="Transaction amount (Encrypted at rest).",
                verbose_name="Amount",
            ),
        ),
    ]
